name: binder-env

channels:
  - conda-forge

dependencies:
  - python=3.11

  # FLEXPART
  - fortran-compiler
  - make
  - pkg-config
  - netcdf-fortran
  - eccodes=2.35.0

  # Python analysis
  - numpy
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - cartopy
